import { Hono } from "hono";
import { toHtml } from "satoru-render/react";
import { render } from "satoru-render";

const app = new Hono();

app.get("/", async (c) => {
  const title = c.req.query("title") || "こんにちは Satoru (Deno)";
  const subtitle = c.req.query("subtitle") || "Denoで爆速画像生成";

  // Define OGP layout using JSX
  const html = toHtml(
    <html>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div
          style={{
            width: "1200px",
            height: "630px",
            position: "relative",
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            background: "linear-gradient(135deg, #1e3a8a 0%, #4c1d95 100%)",
            color: "white",
          }}
        >
          <img
            style={{
              borderRadius: "100%",
              padding: "24px",
              opacity: 0.8,
              position: "absolute",
              display: "flex",
              alignItems: "center",
              justifyContent: "flex-end",
            }}
            width={480}
            height={480}
            src="https://raw.githubusercontent.com/SoraKumo001/cloudflare-ogp/refs/heads/master/sample/image.jpg"
            alt=""
          />
          <div
            style={{
              fontSize: "80px",
              fontWeight: "bold",
              marginBottom: "20px",
              textShadow: "0 8px 16px rgba(0,0,0,0.6)",
              filter: "drop-shadow(0 4px 8px rgba(0,0,0,0.3))",
              backdropFilter: "blur(5px)",
              zIndex: 1,
            }}
          >
            {title}
          </div>
          <div
            style={{
              fontSize: "40px",
              fontWeight: "normal",
              zIndex: 1,
              padding: "12px 12px",
              borderRadius: 24,
              textShadow: "0 8px 16px rgba(0,0,0,0.6)",
              filter: "drop-shadow(0 4px 8px rgba(0,0,0,0.3))",
              backdropFilter: "blur(5px)",
            }}
          >
            {subtitle}
          </div>
          <div
            style={{
              position: "absolute",
              bottom: "40px",
              right: "40px",
              fontSize: "24px",
              fontWeight: "bold",
              padding: "12px 24px",
              background: "rgba(255,255,255,0.1)",
              border: "1px solid rgba(255,255,255,0.2)",
              borderRadius: "12px",
              backdropFilter: "blur(4px)",
              zIndex: 1,
            }}
          >
            Generated by Satoru
          </div>
        </div>
      </body>
    </html>,
  );

  // Render to PNG with automatic font resolution
  const png = await render({
    value: html,
    width: 1200,
    height: 630,
    format: "png",
  });

  return c.body(png.buffer as ArrayBuffer, 200, {
    "Content-Type": "image/png",
    "Cache-Control": "public, max-age=3600",
  });
});

Deno.serve(app.fetch);
