import { Hono } from "hono";
import { Satoru } from "satoru/workerd";
import { toHtml } from "satoru/react";
import React from "react";

const app = new Hono();

// Cache for Satoru instance
let satoru: Awaited<ReturnType<typeof Satoru.init>> | null = null;

app.get("/", async (c) => {
  const title = c.req.query("title") || "こんにちは Satoru";
  const subtitle =
    c.req.query("subtitle") || "Cloudflare Workersで爆速画像生成";

  if (!satoru) {
    satoru = await Satoru.init();
  }

  // Define OGP layout using JSX
  // We include @font-face in a style tag inside the HTML
  const html = `

    ${toHtml(
      <html>
        <head>
          <link
            href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap"
            rel="stylesheet"
          />
        </head>
        <body>
          <div
            style={{
              width: "1200px",
              height: "630px",
              position: "relative",
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
              background: "linear-gradient(135deg, #1e3a8a 0%, #4c1d95 100%)",
              color: "white",
            }}
          >
            <img
              style={{
                borderRadius: "100%",
                padding: "24px",
                opacity: 0.4,
                position: "absolute",
                display: "flex",
                alignItems: "center",
                justifyContent: "flex-end",
                zIndex: -1,
              }}
              width={480}
              height={480}
              src="https://raw.githubusercontent.com/SoraKumo001/cloudflare-ogp/refs/heads/master/sample/image.jpg"
              alt=""
            />
            <div
              style={{
                fontSize: "80px",
                fontWeight: "bold",
                marginBottom: "20px",
                textShadow: "0 4px 12px rgba(0,0,0,0.5)",
              }}
            >
              {title}
            </div>
            <div
              style={{
                fontSize: "40px",
                opacity: 0.9,
                fontWeight: "normal",
              }}
            >
              {subtitle}
            </div>
            <div
              style={{
                position: "absolute",
                bottom: "40px",
                right: "40px",
                fontSize: "24px",
                fontWeight: "bold",
                padding: "12px 24px",
                background: "rgba(255,255,255,0.1)",
                border: "1px solid rgba(255,255,255,0.2)",
                borderRadius: "12px",
                backdropFilter: "blur(4px)",
              }}
            >
              Generated by Satoru
            </div>
          </div>
        </body>
      </html>,
    )}
  `;
  console.log(html);

  // Render to PNG with automatic font resolution
  const png = await satoru.render({
    html,
    width: 1200,
    height: 630,
    format: "png",
    resolveResource: async (resource) => {
      console.log(`Fetching resource: ${resource.url}`);
      const res = await fetch(resource.url);
      if (!res.ok) return null;
      return new Uint8Array(await res.arrayBuffer());
    },
  });

  return c.body(png.buffer as ArrayBuffer, 200, {
    "Content-Type": "image/png",
    "Cache-Control": "public, max-age=3600",
  });
});

export default app;
