import { Hono } from "hono";
import { Satoru } from "satoru/workerd";
import { toHtml } from "satoru/react";
import React from "react";

const app = new Hono();

// Cache for Satoru instance
let satoru: Awaited<ReturnType<typeof Satoru.init>> | null = null;

app.get("/", async (c) => {
  const title = c.req.query("title") || "Hello Satoru";
  const subtitle = c.req.query("subtitle") || "High-performance HTML to Image";

  if (!satoru) {
    satoru = await Satoru.init();
  }

  // Define OGP layout using JSX
  const html = toHtml(
    <div
      style={{
        width: "1200px",
        height: "630px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        color: "white",
        fontFamily: "sans-serif",
      }}
    >
      <div
        style={{
          fontSize: "80px",
          fontWeight: "bold",
          marginBottom: "20px",
          textShadow: "0 4px 8px rgba(0,0,0,0.3)",
        }}
      >
        {title}
      </div>
      <div
        style={{
          fontSize: "40px",
          opacity: 0.9,
        }}
      >
        {subtitle}
      </div>
      <div
        style={{
          position: "absolute",
          bottom: "40px",
          right: "40px",
          fontSize: "24px",
          fontWeight: "bold",
          padding: "10px 20px",
          background: "rgba(255,255,255,0.2)",
          borderRadius: "10px",
        }}
      >
        Generated by Satoru
      </div>
    </div>
  );

  // Render to PNG
  const png = await satoru.render({
    html,
    width: 1200,
    height: 630,
    format: "png",
  });

  return c.body(png.buffer as ArrayBuffer, 200, {
    "Content-Type": "image/png",
    "Cache-Control": "public, max-age=3600",
  });
});

export default app;
